<?php

/**
 * @file
 * Contains paypal_payments.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function paypal_payments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paypal_payments module.
    case 'help.page.paypal_payments':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a way to collect money via paypal on nodes/product entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function paypal_payments_theme() {
  return [
    'paypal_payments' => [
      'render element' => 'children',
    ],

    'field--field-paypal' => [
      'template' => 'field--field-paypal',
      'variables' => ['data' => NULL,],
    ],

    'sdk_page' => [
      'render element' => 'children',
      'template' => 'sdk-page',
      'variables' => [
        'data' => NULL
      ]
    ],
  ];
}

function paypal_payments_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode){

  // Only do this for entities of type Node.
  if ($entity instanceof NodeInterface) {
    $build['extra_markup'] = [
      '#markup' => 'this is extra markup HERE NPOW',
    ];
  }
}