<?php

namespace Drupal\paypal_payments\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form controller for Paypal edit forms.
 *
 * @ingroup paypal_payments
 */
class PaypalForm extends ContentEntityForm {

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    /* @var $entity \Drupal\paypal_payments\Entity\Paypal */
    $form = parent::buildForm($form, $form_state);

    $entity = $this->entity;

    $form['actions']['submit']['#value'] = $this->t('Pay with PayPal');
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    return parent::validateForm($form, $form_state); // TODO: to VALIDATE SHIT
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {
    $entity = $this->entity;

    $status = parent::save($form, $form_state);

    switch ($status) {
      case SAVED_NEW:
        drupal_set_message($this->t('Created the %label Paypal.', [
          '%label' => $entity->label(),
        ]));
        break;

      default:
        drupal_set_message($this->t('Saved the %label Paypal.', [
          '%label' => $entity->label(),
        ]));
    }
    $form_state->setRedirect('entity.paypal.canonical', ['paypal' => $entity->id()]);
  }

}
